### ISSUE TITLE
Code to generate l1000.db or the downloadable l1000.db

### ISSUE THREAD

**Issue by zhilongjia** [dhimmel/lincs#2]
As shown in database.ipynb, there is a large-size l1000.db file, containing the gene expression profiles and meta data of lincs. Here could you publish the code to produce the l1000.db and/or the l1000.db itself? Thank you.

**Comment by dhimmel** [comment]
This reply is in the context of the repository at commit 093dc3a0497028ad2b9549a3f9fa12f8ce38461f.

## Database contents

`l1000.db` contains the following tables:
- `cells`: observations are cell types
- `perts`: observations are pertrubagens
- `sigs`: observations are signatures
- `similarities`: observations are perturbagen pairs
- `unichem`: observations are perturbagen to external identifier mappings

`similarities` and `unichem` only have information for small molecule compounds with InChI strings.

Currently, the database does not contain any gene information (such as differential expression). If you want our consensus expression signatures, [look here](http://doi.org/10.15363/thinklab.d43#6).

## Downloading `l1000.db`

I didn't originally upload the database because of it's size (18.4 GB). If anyone knows of a free repository for large files, let us know. I've posted the database file for download (http://dipper.ucsf.edu/l1000.db). This location is only temporary, so don't rely on its permanence.

## Recreating `l1000.db`

If you clone the repository, you should be able the recreate the database by running the following notebooks in order (written for Python 3.4):
1. `database.ipynb`
2. `unichem.ipynb`
3. `chemical-similarity.ipynb`

**Comment by zhilongjia** [comment]
Done. Thank you.
